### ISSUE TITLE
Url listed on https://linuxgsm.com for each game is a non working URL

### ISSUE THREAD

**Issue by gjdunga** [GameServerManagers/LinuxGSM-Support#13]
Hello, 
**This error has to do with the website https://linuxgsm.com, not the code in the repo.** 

The URL is malformed for the user to download the script, for each and every game. 

The URL that is listed on the website is:   (Rust used as an example) 

`wget -O linuxgsm.sh https://linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh rustserver`

Please see the Image attached that shows the error and an arrow has been added to point to the issue. 
(A different game instruction page is shown to further impress that this is a site-wide error. ) 

![LGSM_URL_ISSUE_2019-06-06](https://user-images.githubusercontent.com/527080/59011786-fc863500-87f2-11e9-9061-87d458aad413.png)

I know how to get it from the git repo, but I'm sure many will not know how to do this.

**Comment by dgibbs64** [comment]
I have been using this without any issues. Likey an issue with your server

**Comment by gjdunga** [comment]
Dgibbs64 it is not the script. It is the website that is incorrectly written.

**Comment by dgibbs64** [comment]
The domain simply redirects to the GitHub URL. I use the link all the time and don't have issues. Please provide output of the error.

**Comment by gjdunga** [comment]
Dgibbs64.

Okay, let me ask this another way. do you own the url https://linuxgsm.sh and does it directly link to the script?  This should be obvious. The url on the webpage is malformed.

**Comment by gjdunga** [comment]
![Capture+_2019-06-16-18-15-45](https://user-images.githubusercontent.com/527080/59571574-7c1dca80-9063-11e9-8813-400f0f5da60d.png)

**Comment by gjdunga** [comment]
The command should be something like:
wget -O linuxsgm.sh https://github.com/GameServerManagers/LinuxGSM/blob/develop/linuxgsm.sh && chmod +x linuxgsm.sh && bash linuxgsm.sh rustserver

I do not know if you have an alias or softlink somewhere but what is on the website does not work.

**Comment by h3o66** [comment]
in your comment
https://github.com/GameServerManagers/LinuxGSM-Support/issues/13#issuecomment-502498287

The link is wrong so i am not sure what you want.

The domain linuxgsm.sh is working for me as expected (this does a redirect to github.com).

**Comment by gjdunga** [comment]
Closing the ticket: The link as documented on the site is now working... 

I apologize if I came off as annoying or demanding. I was simply trying to make sure others are able to use the product, as it's decent.

**Comment by dgibbs64** [comment]
As I said before it looked like an issue on your end since you are the only person to report the issue. If it was broken I would get many people reporting it all at once. I also use the link all the time being the lead developer ;). Glad you enjoy using LinuxGSM
