### ISSUE TITLE
Rust server setup help (first time setting up a server)

### ISSUE THREAD

**Issue by longjabari** [GameServerManagers/LinuxGSM-Support#22]
Having troubles with the wget part

![help](https://user-images.githubusercontent.com/25539750/65458808-6a934e00-de1c-11e9-8feb-a2af3570a01f.png)

**Comment by dgibbs64** [comment]
There is something very wrong with your distro. May be worth reinstalling if possible. Maybe use CentOS or ubuntu instead of scientific linux.

**Comment by kennyLtv** [comment]
Actually I think it's far simpler. 

`wget -o` won't work it needs to be `wget -O` it's not a 0 it's a capital o.

**Comment by longjabari** [comment]
Thank you I figured it out
