### ISSUE TITLE
CS 1.6 server playable on LAN only

### ISSUE THREAD

**Issue by coult45usmc** [GameServerManagers/LinuxGSM-Support#24]
I'm running CSGO, TF2, Garry's Mod. All servers run fine and are viewable/playable from the web. CS 1.6 installs without issue and allows local players to join, but it's not detectable from the web. I inspected packets at WAN and LAN interfaces. No traffic is blocked. 
server ports: CSGO = 27015, GMOD = 27016, TF2 = 27017, CS 1.6 = 27018
I've switched the ports around. Same result. 
[csserver-console.log](https://github.com/GameServerManagers/LinuxGSM-Support/files/3692837/csserver-console.log)
[WAN packet capture.txt](https://github.com/GameServerManagers/LinuxGSM-Support/files/3692838/WAN.packet.capture.txt)

**Comment by gaudreaurm** [comment]
The packet capture is only from a single WAN interface. Please gather concurrent captures from the NATing gateway (136.33.3.53) and also the server itself (10.10.3.18)

**Comment by coult45usmc** [comment]
Thanks for replying. Attached is the info you requested. Let me know if you need anything else. The pcap files were saved with Wireshark after capturing traffic from the LAN switch interface that the server is connected to. I did one while connecting from the LAN and one while trying to connect from the Internet. I've tried this using multiple different operating systems: Fedora/Debian/Ubuntu 64 and 32bit. All had the same result (LAN but no WAN connections). My current OS is 32bit Debian with no iptables. I would have included some logs from the server but after looking through several logs to include syslog and debug, there was nothing there of substance related to this issue. 
![from Internet](https://user-images.githubusercontent.com/35446561/66703810-1c1af600-ecdc-11e9-8156-e8a6970500b5.jpg)
![LAN capture](https://user-images.githubusercontent.com/35446561/66703811-1c1af600-ecdc-11e9-9235-c564245aaad5.png)
[info.txt](https://github.com/GameServerManagers/LinuxGSM-Support/files/3720847/info.txt)

**Comment by coult45usmc** [comment]
I would love for someone to grab any version of Fedora or Debian and see if you can get the CS1.6 server to accept connections from the Internet. I'm convinced that it's not my network, or the OS, since everything works well with all of the other servers I'm running. At one point I tried the CS1.6 server on the same VM that my CSGO server was using (different user, different port). It still didn't work, but CSGO worked fine.

**Comment by gaudreaurm** [comment]
Since the server is accessible on the LAN, I do not see this being an issue with the server itself. Typically I would look at ruling out a NAT/Firewall/ACL issue. 


To test this let's try another filter (assuming this is the only cs1.6 server in your network). You can do this on the caps you already gathered.

try this filter: udp.port eq 27018 || tcp.port eq 27018

What type of device is performing the NAT? any security policy in effect anywhere in the flow?

Also, just checking... You did attempt to connect when you gathered the capture, correct?

**Comment by coult45usmc** [comment]
Yes, I'm connecting during the captures. Oddly enough, you can see the TCP connections with the Valve server, but no UDP traffic. Not sure why. I agree, I'm tempted to focus on the NAT/Firewall (and believe me I have been) however, I've already confirmed it's all working as desired for the other servers. I actually have a CS 1.6 server on the same exact Fedora VM as the CSGO server that's working great. I shut down the CSGO server, and start up the CS1.6 using the same port (27015) and it won't work. The only thing being different between a working situation and a non working situation is the CS 1.6 script/software.

**Comment by coult45usmc** [comment]
Here's the difference between a working and non-working server on the WAN interface:

udp      17 22 src=174.234.14.193 dst=136.33.3.53 sport=10954 dport=27015 src=10.10.3.15 dst=174.234.14.193 sport=27015 dport=10954 mark=0 use=1

udp      17 13 src=174.234.14.193 dst=136.33.3.53 sport=10974 dport=27018 [UNREPLIED] src=10.10.10.1 dst=174.234.14.193 sport=27018 dport=10974 mark=0 use=1

the server is not repling to UDP traffic

**Comment by coult45usmc** [comment]
I figured it out. I run Cisco Call Manager Express at my house with a SIP trunk out to callcentric.com. It uses UDP-RTP port range 16384 to 32767. See the issue now? Not sure why it only adversely affected the CS 1.6 software. All of the other game servers have ports in this range too, but worked fine. It turns out the CME doesn't need any of those ports forwarded anyway so I just deleted that NAT rule. 

If you look at this packet capture from my WAN interface, you can see my router properly forwarding the UDP traffic (172.234.14.193 is me tethered to my cell, 10.10.3.15 is my CSGO server using port 27015):
udp      17 22 src=174.234.14.193 dst=136.33.3.53 sport=10954 dport=27015 src=10.10.3.15 dst=174.234.14.193 sport=27015 dport=10954 mark=0 use=1

Now look at this capture for CS 1.6. "10.10.10.1" is my Call Manager. 

udp      17 13 src=174.234.14.193 dst=136.33.3.53 sport=10974 dport=27018 [UNREPLIED] src=**_10.10.10.1_** dst=174.234.14.193 sport=27018 dport=10974 mark=0 use=1
