### ISSUE TITLE
Using MOHAA ubuntu installer get lib errors

### ISSUE THREAD

**Issue by dayoftheduck** [GameServerManagers/LinuxGSM-Support#33]
lib32gcc1
libstdc++6:i386
libstdc++5:i386
Warning! Missing dependencies: lib32gcc1 libstdc++6:i386 libstdc++5:i386

**Comment by dgibbs64** [comment]
You haven't installed the dependencies.

**Comment by dayoftheduck** [comment]
The SSH program won't let me paste this into line to build. sudo dpkg --add-architecture i386; sudo apt update; sudo apt install mailutils postfix curl wget file tar bzip2 gzip unzip bsdmainutils python 
util-linux ca-certificates binutils bc jq tmux lib32gcc1 libstdc++6 libstdc++6:i386

**Comment by dayoftheduck** [comment]
finally got it installed but now i can't connect but it shows that it set my net_ip and log says everything is online

**Comment by Frisasky** [comment]
ok, i would check this game as i added this game to lgsm, currently im super busy so i cant provide a ETA sry

**Comment by dayoftheduck** [comment]
I don’t think it’s your end, the game launches but I can’t connect I did a
tracert and I’m not getting a response on a few hops so I believe it’s my
network
